### ISSUE TITLE
Making this repository public.

### ISSUE THREAD

**Issue by RaghavTheCyberdude** [nilinswap/neuro-evolution#18]
As we had originally intended, and since now Kala sir requires us to submit our codes, let's make this repository public.

Things to do:

- [x] Copy the readme to post-midsem branch, get rid of master branch.
- [x] Rename post-midsem as master.
- [x] Cleanup a little bit.
- [ ] Add documentation. (code is self documented, but still)
- [ ] Integrate Travis CI, get build report functioning.
- [ ] profit???

**Comment by nilinswap** [comment]
@RaghavTheCyberdude  do the necessary and close this issue afterwards.
